### ISSUE TITLE
Add a link to the TodoMVC examples

### ISSUE THREAD

**Issue by arthurvr** [gianarb/awesome-angularjs#45]
I figured TodoMVC deserves a place on the list. There are 6 Angular examples:

* [angular-dart](https://github.com/tastejs/todomvc/tree/master/examples/angular-dart)
* [angular2](https://github.com/tastejs/todomvc/tree/master/examples/angular2)
* [angularjs-perf](https://github.com/tastejs/todomvc/tree/master/examples/angularjs-perf)
* [angularjs](https://github.com/tastejs/todomvc/tree/master/examples/angularjs)
* [angularjs_require](https://github.com/tastejs/todomvc/tree/master/examples/angularjs_require)
* [typescript-angular](https://github.com/tastejs/todomvc/tree/master/examples/typescript-angular)

**Comment by gianarb** [comment]
Oh yes.. can you submit a PR? :)
Thanks
