### ISSUE TITLE
Reformat to Contribution Standards

### ISSUE THREAD

**Issue by JimmyBoh** [gianarb/awesome-angularjs#54]
Currently this list is a little wild, various versions of "Angular", "AngularJS", "angular.js", etc, as well as many lines without endings.

The basic clean up items are as follows:

 - [x] Check and update all links.
 - [x] Change all variations of `angular`'s title  to one version.
 - [x] Add "." to the end of each description.

Regarding the name of `angular` in the list, we should adjust to make them all the same. Here are the options, please let me know which is the appropriate style.

 - Angular
 - AngularJS
 - Angular.js
 - angular
 - angularjs
 - angular.js

I will have a pull request coming shortly for the basic formatting, and once I hear back from @gianarb and others about what to call `angular` I will wrap it all up.

**Comment by gianarb** [comment]
Hello @JimmyBoh thanks for your feedback but the "name of angular" in my opinion is not a big problem because the role is very clear

<ownerRepo>/<repoName>

:) Why this is a problem?

**Comment by JimmyBoh** [comment]
Hey @gianarb I like consistency =]. If you don't think it needs it then I'll leave them as is.

**Comment by gianarb** [comment]
@JimmyBoh thanks but in my opinion this problem of "consistency" not exist...

The nomenclature is consistent with `<ownerRepo>/<repoName> :)

**Comment by JimmyBoh** [comment]
Oh, no that is fine, I mean all the different names for AngularJS. For example, from the "Directives" section (bolded for emphasis):

* [djds4rce/angular-socialshare](https://github.com/djds4rce/angular-socialshare) - Social share buttons for **angularjs**.
* [blackgate/bg-splitter](https://github.com/blackgate/bg-splitter) - Simple pane splitter for **angular.js**.
* [fullscale/dangle](https://github.com/fullscale/dangle) - A set of **AngularJS** directives that provide common D3 visualizations for elasticsearch.

As you can see, there is no standard name being used, everything is different case, with or without "JS", etc.

**Comment by JimmyBoh** [comment]
@gianarb Any thoughts after looking at my example above?
