### ISSUE TITLE
Flow support for angularjs

### ISSUE THREAD

**Issue by sibeliusseraphini** [gianarb/awesome-angularjs#61]
Is there any package to support [Flow](http://flowtype.org/) in AngularJS?

**Comment by gianarb** [comment]
I saw this library, but I don't know if it is supported yet

https://github.com/solnetdigital/flow-interfaces-angular

**Comment by sibeliusseraphini** [comment]
it is not working

**Comment by gianarb** [comment]
Sorry I doesn't know other libraries :)

**Comment by sibeliusseraphini** [comment]
thank you
