### ISSUE TITLE
Suggestion: link timestamping

### ISSUE THREAD

**Issue by dmitriz** [gianarb/awesome-angularjs#66]
May I suggest to add time stamps next to the links, when they were last updated?

Especially with Angular, things move very fast and many posts grow old, and with such a long list it is very hard to know which are the recent ones.

**Comment by gianarb** [comment]
Hello, Thanks for your suggestion but this information is already save in git.
Search in its history please

http://stackoverflow.com/questions/2928584/how-to-grep-search-committed-code-in-the-git-history
